volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ffgpa2/taski_backend
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - static:/app/collected_static

  frontend:
    image: ffgpa2/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: ffgpa2/taski_gateway
    env_file: .env
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - 9090:80
    volumes:
      - static:/static